Run actions/github-script@v6
  with:
    script: try {
    await github.rest.actions.createWorkflowDispatch({
      owner: context.repo.owner,
      repo: context.repo.repo,
      workflow_id: 'build_release.yml',
      ref: 'main'
    })
  } catch (error) {
    // 添加详细错误日志输出
    console.error("触发工作流失败:", error);
    console.error("请检查PAT_TOKEN是否已设置并具备workflow权限");
    core.setFailed(error.message);
  }
  
    debug: false
    user-agent: actions/github-script
    result-encoding: json
    retries: 0
    retry-exempt-status-codes: 400,401,403,404,422
  env:
    REMOTE_HASH: e2bea8a2b2b441cb3dd4adb576023935e68a593b
    changes_detected: true
